# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  dhi:
    type: docker-registry
    url: https://dhi.io
    username: ${{secrets.DOCKER_USER}}
    password: ${{secrets.DOCKER_PAT}}
    replaces-base: true
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    assignees:
      - mkaraki
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    assignees:
      - mkaraki
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    assignees:
      - mkaraki
    schedule:
      interval: "monthly"
    registries: "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - mkaraki

