[package]
name = "narourb_webview"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version= "4.11.0", default-features = false, features = ["macros", "unicode"] }
git2 = { version = "0.20.2", default-features = false }
sentry = { version = "0.45.0", features = ["actix", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
actix-files = "0.6.8"
tokio = { version = "1.48.0", features = ["fs"] }
chrono = { version = "0.4.42", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-saphyr = "0.0.10"
rayon = "1.11.0"
cached = { version = "0.56.0", features = ["async"] }
